image:
  repository: logicmonitor/lm-logs-k8s-fluentd
  pullPolicy: IfNotPresent
  tag: "0.0.12"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env: {}

resources:
  limits:
    memory: 1000Mi
  requests:
    cpu: 300m
    memory: 700Mi
fluent:
  buffer:
    memory:
      flush_interval: 1s
      chunk_limit_size: 8m
      flush_thread_count: 8

nodeSelector: []
affinity: []
tolerations:
 - operator: Exists

