image:
  repository: logicmonitor/lm-logs-k8s-fluentd
  pullPolicy: IfNotPresent
  tag: "0.0.12"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 200Mi

tolerations:
  - operator: Exists

