apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
{{- if .Values.labels}}
{{ toYaml .Values.labels| indent 4 }}
{{- end }}
data:
  logicmonitor_account: {{ required "A valid .Values.lm.lm_account entry is required!" .Values.lm.lm_account }}
  lmotel_name: {{ required "A valid .Values.lm.lm_otel_name entry is required!" .Values.lm.lm_otel_name }}
  {{- if .Values.lm.lm_collector_id }}
  lm_collector_id: {{ .Values.lm.lm_collector_id | quote}}
  {{ end }}

