apiVersion: v1
kind: ConfigMap
metadata:
  name: collectorset-controller
  labels:
    chart: "collectorset-controller"
  annotations:
    helm-chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    helm-revision: "{{ .Release.Revision }}"
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
data:
  config.yaml: |
    debug: {{ required "A valid .Values.debug entry is required!" .Values.debug }}
    {{- if .Values.proxyURL }}
    proxy_url: {{ .Values.proxyURL }}
    {{- end }}
