apiVersion: v1
kind: ConfigMap
metadata:
  name: collectorset-controller
  labels:
    chart: "collectorset-controller"
  annotations:
    helm-chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    helm-revision: "{{ .Release.Revision }}"
    ## keep value false as string, spinnaker's limitation, otherwise spinnaker fails to cast boolean to string
    strategy.spinnaker.io/versioned: "false"
data:
  config.yaml: |
    debug: {{ required "A valid .Values.debug entry is required!" .Values.debug }}
    {{- if .Values.proxyURL }}
    proxy_url: {{ .Values.proxyURL }}
    {{- end }}
