{{- if .Values.enableRBAC -}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: collectorset-controller
rules:
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - "*"
- apiGroups:
    - "apps"
  resources:
    - statefulsets
  verbs:
    - "*"
- apiGroups:
    - "*"
  resources:
    - collectorsets
  verbs:
    - "*"
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: collectorset-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collectorset-controller
subjects:
- kind: ServiceAccount
  name: collectorset-controller
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: collector
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - containers
  - nodes
  - componentstatuses
  - replicasets
  - ingress
  - services
  - endpoints
  verbs:
  - list
  - get
- apiGroups:
  - "apps"
  - "extensions"
  resources:
  - deployments
  verbs:
  - list
  - get
- apiGroups:
    - "autoscaling"
  resources:
    - horizontalpodautoscalers
  verbs:
    - list
    - get
- apiGroups:
  - ""
  resources:
  - nodes/stats
  verbs:
  - get
- apiGroups:
  - "discovery.k8s.io"
  resources:
  - endpointslices
  verbs:
  - list
  - get
- nonResourceURLs:
  - /
  - /healthz
  - /healthz/*
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collector
subjects:
- kind: ServiceAccount
  name: collector
  namespace: {{ .Release.Namespace }}
{{- end -}}
