imageRepository: logicmonitor/argus
imageTag: v2
imagePullPolicy: Always
disableAlerting: false
deleteDevices: true
debug: false
enableRBAC: true
nodeSelector: {}
affinity: {}
priorityClassName: ""
collector:
  imageRepository: logicmonitor/collector
  imageTag: latest
  imagePullPolicy: Always
  secretName: collector
  priorityClassName: ""
