imageRepository: logicmonitor/argus
imageTag: v4
imagePullPolicy: Always
disableAlerting: false
deleteDevices: true
debug: false
enableRBAC: true
clusterName: ""
accessID: ""
accessKey: ""
account: ""
etcdDiscoveryToken: ""
proxyUser: ""
proxyPass: ""
proxyURL: ""
clusterGroupID: 0
nodeSelector: {}
affinity: {}
priorityClassName: ""
tolerations: []
annotations: {}
labels: {}
filters:
  pod: ""
  service: ""
  node: ""
  deployment: ""
collector:
  imageRepository: logicmonitor/collector
  imageTag: latest
  imagePullPolicy: Always
  secretName: collector
  replicas: 1
  size: ""
  groupID: 0
  escalationChainID: 0
  collectorVersion: 0
  useEA: false
  proxyURL: ""
  proxyUser: ""
  proxyPass: ""
  priorityClassName: ""
  tolerations: []
