imageRepository: logicmonitor/argus
imageTag: v1
imagePullPolicy: Always
disableAlerting: false
deleteDevices: true
debug: false
enableRBAC: true
nodeSelector: {}
affinity: {}
collector:
  imageRepository: logicmonitor/collector
  imageTag: latest
  imagePullPolicy: Always
  secretName: collector