# Default values for lmotel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

lm:
  lm_account: ""
  lm_bearer_token: ""
  lm_otel_name: ""
  lm_collector_id: 0

image:
  # TODO: Change the repo from docker-registry to dockerhub once it is pushed to dockerhub
  repository: docker-registry.logicmonitor.net/development/lm-otel
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0"

service:
  type: ClusterIP
  name: lmotel-svc
  ports:
    http: 55681
    grpc: 55680

labels: {}
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
