imageRepository: logicmonitor/collectorset-controller
imageTag: v1
imagePullPolicy: Always
debug: false
enableRBAC: true
accessID: ""
accessKey: ""
account: ""
etcdDiscoveryToken: ""
proxyUser: ""
proxyPass: ""
proxyURL: ""
nodeSelector: {}
affinity: {}
priorityClassName: ""
tolerations: []
